### ISSUE TITLE
broken link to example in readme

### ISSUE THREAD

**Issue by darcien** [gregsdennis/dependencies-action#11]
Hello, thanks for creating this cool action

I opened the link to the example in the readme, it leads me to the wrong page like:
![image](https://user-images.githubusercontent.com/19742419/148752135-6563baec-7c51-4407-98cf-b6026f3baa16.png)

Caused by the extra s in the url (i.e. should be pull/5 instead of pulls/5)

Should be easy to fix, I can submit a PR if you want

Cheers

**Comment by gregsdennis** [comment]
Thanks for finding this. A PR would be welcome!
