### ISSUE TITLE
Node.js 12 deprecation

### ISSUE THREAD

**Issue by eruizalo** [gregsdennis/dependencies-action#14]
We are getting this warning using this action (v1.2.3) for some time:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: gregsdennis/dependencies-action

**Comment by gregsdennis** [comment]
Thanks for the report. Guess I missed this one.  I'll update soon.
