### ISSUE TITLE
ability to add custom regex for identifiying lines

### ISSUE THREAD

**Issue by ilyesAj** [gregsdennis/dependencies-action#16]
we're using GHE enterprise, and we're unable to use this GitHub actions workflow since it's using a specific github.com regex. 
https://github.com/gregsdennis/dependencies-action/blob/main/index.js#L9
https://github.com/gregsdennis/dependencies-action/blob/main/index.js#L10

is it possible to either:
- Define a custom regex that we can inject using global env variable 
- Make the GitHub url within the regex as a variable so that we can override it if needed  

Example of link for a PR on Github enterprise: https://mygheurl.com/OWNER/REPO_NAME/pull/3

**Comment by gregsdennis** [comment]
Hi, thanks for the suggestion.

I think I can set it up for you to include custom domains as a parameter, but I don't think it's a good idea to support the user imputting their own regex.  The logic is pretty tightly coupled to specific groups within the regex, and if those are missing or misaligned, then the action can't work.
