### ISSUE TITLE
Make workflow work when PR is opened from fork

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [gregsdennis/dependencies-action#19]
When u create a PR from a fork the workflow will not run. 
Please make it possible for the workflow to run when a pr is created from a fork

**Comment by gregsdennis** [comment]
Can you elaborate on "will not run"?  What do you mean by this?  Does it run but fail, or does it just not run at all?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
it does not run at all

**Comment by gregsdennis** [comment]
I think that's a repository/fork setting, and not something to do with this action.

Please see

- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
- https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
See https://github.com/gregsdennis/dependencies-action/pull/20

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> I think that's a repository/fork setting, and not something to do with this action.
> 
> Please see
> 
>     * https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> 
>     * https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

This is actually not true we have workflows running in our repo that work fine when a PR is opened from fork
See https://github.com/FreeTubeApp/FreeTube/blob/development/.github/workflows/conflicts.yml

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Its working -.- Welp apologies for taking your time i clearly misconfigured it somehow

**Comment by gregsdennis** [comment]
> we have workflows running in our repo that work fine when a PR is opened from fork

I've noticed in other repos that some workflows run automatically from forks while others don't.  I'm not sure what the criteria is for that to occur.  I can explore that.
