### ISSUE TITLE
Second PR dependency is not matched/checked

### ISSUE THREAD

**Issue by leocencetti** [gregsdennis/dependencies-action#22]
# Current Behavior
When listing multiple PR dependencies by full URL, only the first one is matched and checked, independently of whether it's merged or not.
# Expected Behavior
All dependencies are matched/checked
# Example
I've set up an [example repository](https://github.com/leocencetti/pr_deps_check_example) that replicates this issue.
The repo has 3 open PRs that target `main` and depend on each other as such:
```mermaid
graph LR
PR1 ---> PR3
PR2 ---> PR3
``` 
In the [PR3](https://github.com/leocencetti/pr_deps_check_example/pull/3)  checks, you can see the following output (from this action):
```
[...]
Found full-url dependency in 'Depends on https://github.com/leocencetti/pr_deps_check_example/pull/1'
Found no dependency in 'Depends on https://github.com/leocencetti/pr_deps_check_example/pull/2'
[...]
```
note the `Found no dependency` line. 

As mentioned before, the behavior is the same if `PR1` is merged, or the order is swapped.

**Comment by leocencetti** [comment]
The issue seems to be related to the line endings. With an empty line between dependencies it works as expected.

**Comment by gregsdennis** [comment]
Well, that's odd.  I'll have a look.

**Comment by gregsdennis** [comment]
I can't edit posts in that repo, so I can't get the exact markdown.  @leocencetti does the text have a blank line at the end?

**Comment by gregsdennis** [comment]
I've restructured a bit so that I can add some tests.  It looks like the issue is not having a blank line at the end.  Not sure why that's a problem.

Of three multi-line tests, two have failed:

- Shorthand and partial link ❌
    ```js
    const shorthandAndPartialLink = `Depends on #14
    Depends on gregsdennis/dependencies-action#5`
    ```
- Shorthand and partial link with blank line at end ✔️
    ```js
    const shorthandAndPartialLinkWithBlankLineAtEnd = `Depends on #14
    Depends on gregsdennis/dependencies-action#5
    `
    ```
- Shorthand and partial link with blank line in middle ❌
    ```js
    const shorthandAndPartialLinkWithBlankLineInMiddle = `Depends on #14

    Depends on gregsdennis/dependencies-action#5`
    ```

**Comment by gregsdennis** [comment]
Looks like that's the issue, though I'm not sure what's going on b/c JS isn't my strength.

```js
const simpleRegex = new RegExp(`abc`, 'gmi');
const body = `abc
123
abc123
abc`;
const ls = body.split(splitDelimiter);
ls.forEach(line => {
    const match = simpleRegex.exec(line);
    console.log(match);
});
```

outputs

```
  console.log
    [ 'abc', index: 0, input: 'abc', groups: undefined ]

      at log (evaluate-dependencies.test.js:22:13)
          at Array.forEach (<anonymous>)

  console.log
    null

      at log (evaluate-dependencies.test.js:22:13)
          at Array.forEach (<anonymous>)

  console.log
    [ 'abc', index: 0, input: 'abc123', groups: undefined ]

      at log (evaluate-dependencies.test.js:22:13)
          at Array.forEach (<anonymous>)

  console.log
    null

      at log (evaluate-dependencies.test.js:22:13)
          at Array.forEach (<anonymous>)
```

Note the last match attempt fails.

([fiddled](https://jsfiddle.net/dr0tv2cL/))

**Comment by gregsdennis** [comment]
Okay.  Restructured to just find all matches for each regex across the entire body at once.  It works now.

I still don't understand why the line splitting version fails, and I don't really care.

**Comment by leocencetti** [comment]
> Okay. Restructured to just find all matches for each regex across the entire body at once. It works now.

Perfect, thank you for the quick fix!
