### ISSUE TITLE
hotfix needs for uuid

### ISSUE THREAD

**Issue by kevin-li-unloan** [gregsdennis/dependencies-action#24]
https://github.com/gregsdennis/dependencies-action/blob/main/node_modules/.bin/uuid   is symlink

**Comment by gregsdennis** [comment]
I don't understand. Can you elaborate on what the actual problem is?

**Comment by leocencetti** [comment]
@gregsdennis the action setup fails with:
```
Current runner version: '2.310.2'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'gregsdennis/dependencies-action@1.3.1' (SHA:[2](https://github.com/fbx-org/MAVLink-mavros/actions/runs/6557743369/job/17810206240#step:1:2)8d95779f2ba3e9197184e0d917984b810943f[6](https://github.com/fbx-org/MAVLink-mavros/actions/runs/6557743369/job/17810206240#step:1:7)e)
Error: Could not find file '/home/runner/work/_actions/_temp_e073b0b6-f1c3-475f-9316-2450052bd601/_staging/gregsdennis-dependencies-action-28d9577/node_modules/.bin/uuid'.
```

**Comment by leocencetti** [comment]
As @kevin-li-unloan said, the `uuid` script under `node_modules/.bin` is a symlink (GitHub shows it nicely [here](https://github.com/gregsdennis/dependencies-action/tree/main/node_modules/.bin)).

**Comment by gregsdennis** [comment]
Hm... I wonder if I can leave the test dependencies out of the repo.

The docs say that `node_modules` needs to be checked in, but just adding `jest` added a LOT of packages.  Given that it's not needed to run the action, maybe I can just remove those.

I'll work on that tomorrow.  In the meantime, pin the version in your YAML file.

**Comment by leocencetti** [comment]
Did some digging in the repo sources and the symlink seems indeed broken/invalid (it points to an inline script):

![image](https://github.com/gregsdennis/dependencies-action/assets/37414873/2c35b18e-4fd7-48a6-9032-383f0cf9247b)

It should be enough to replace it with a regular file containing the current target script (same as for `uuid.cmd` and `uuid.ps1` files in the same dir).

**Comment by gregsdennis** [comment]
@leocencetti fyi

**Comment by gregsdennis** [comment]
I did a clean removal and reinstall of all of the npm modules.  Will publish again.

**Comment by gregsdennis** [comment]
Looks to be working now.  Let me know if you continue to have problems.

cc: @kevin-li-unloan @leocencetti @Czaki @bprather

**Comment by c-prather** [comment]
Looks to be working for us.  Thanks!
