### ISSUE TITLE
Node.js 16 deprecation

### ISSUE THREAD

**Issue by leocencetti** [gregsdennis/dependencies-action#25]
Similarly to https://github.com/gregsdennis/dependencies-action/issues/14, `Node.js 16` is now deprecated as well. Here is the warning for reference:
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: gregsdennis/dependencies-action@1.3.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by gregsdennis** [comment]
Thanks. If you like, I'm happy to accept a PR.

**Comment by reneoun** [comment]
@gregsdennis You have made a very nice Github Action! 🚀
Could you release the latest version of main with a new version tag? 
We would like to fix node16 deprecation warning.

![image](https://github.com/gregsdennis/dependencies-action/assets/43538982/c2166aba-c60a-4a3d-be54-9c5dbb55c49b)

We have already tried to add this:
`- uses: gregsdennis/dependencies-action@main`
But this will still redirect to version 1.3.0 & also version 1.3.2 is still running on node16

**Comment by gregsdennis** [comment]
Sorry for not publishing.  v1.3.3 is now available and is set to the primary release.
