### ISSUE TITLE
only returns first found not all

### ISSUE THREAD

**Issue by jon-nfc** [gregsdennis/dependencies-action#28]
when there is more than one "depends on" within the body of the PR, only the first one is found. see [here](https://github.com/nofusscomputing/centurion_erp/actions/runs/10317133439/job/28560748862). All should be returned.

**Comment by gregsdennis** [comment]
It was working fine for me earlier this week.  See https://github.com/json-everything/json-everything/pull/775

**Comment by gregsdennis** [comment]
Are you using `-` or `*` for the bullets.  It doesn't look like `*` is supported.  (I'll fix that.)

Are you saying that only the first open issue/PR is reported, but you expect _all_ open issues/PRs to be reported?  ([That](https://github.com/json-everything/json-everything/actions/runs/10225414008/job/28294409500) seems to be working as well.)

**Comment by jon-nfc** [comment]
> Are you using `-` or `*` for the bullets. It doesn't look like `*` is supported. (I'll fix that.)
> 
> Are you saying that only the first open issue/PR is reported, but you expect _all_ open issues/PRs to be reported? ([That](https://github.com/json-everything/json-everything/actions/runs/10225414008/job/28294409500) seems to be working as well.)

using `-` and use only the first open. see workflow -> https://github.com/nofusscomputing/centurion_erp/actions/runs/10317133439/job/28560748862

**Comment by gregsdennis** [comment]
Yes, I'm looking at that build.  I'm not sure why it's only seeing one.  If you can post the markdown of that PR, I'll see if I can figure out what's going on.

**Comment by jon-nfc** [comment]
the PR is : https://github.com/nofusscomputing/centurion_erp/pull/216

markdown

``` md

This PR is to complete the migration from Gitlab to Github

## Links

- Blocked by: https://github.com/nofusscomputing/action_docker/pull/1
- Blocked by: https://github.com/nofusscomputing/action_bump/pull/1
- Blocked By https://github.com/nofusscomputing/action_python/pull/1
- Blocked By: https://github.com/nofusscomputing/action_pull_requests/pull/1
- Related: https://github.com/gregsdennis/dependencies-action/issues/28
- Related: #213 
- Related: #214 

/cc @jasonpagetas 
```

```

**Comment by gregsdennis** [comment]
Okay.  The problem is the colons: they're not expected.  Only the third one doesn't have a colon.

I can fix that, but for now, just remove them.

**Comment by jon-nfc** [comment]
> Okay. The problem is the colons: they're not expected. Only the third one doesn't have a colon.
> 
> I can fix that, but for now, just remove them.

Awesome. Thanks, ill remove for now. I do intend on having them there so await a fix.

**Comment by gregsdennis** [comment]
Alright v1.4.0 is now available.  Please close after testing.

**Comment by jon-nfc** [comment]
> Alright v1.4.0 is now available. Please close after testing.

got an error with it

``` text
Current runner version: '2.317.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'gregsdennis/dependencies-action@f4fa19405413bddd[2](https://github.com/nofusscomputing/centurion_erp/actions/runs/10317843346/job/28562944523#step:1:2)d49fe258f5b571de44cac09' (SHA:f4fa19405413bddd2d49fe258f5b571de44cac09)
Error: Could not find file '/home/runner/work/_actions/_temp_78243827-fb9f-4212-9c85-e8c32a702aeb/_staging/gregsdennis-dependencies-action-f4fa194/node_modules/.bin/esparse'.

```

workflow: https://github.com/nofusscomputing/centurion_erp/actions/runs/10317843346/job/28562944523

**Comment by gregsdennis** [comment]
I'll have to look in the morning. Going to bed now.

**Comment by jon-nfc** [comment]
Awesome. thanks again for your time. It's appreciated!!

**Comment by fmauri-shippypro** [comment]
Same error on our side

**Comment by jon-nfc** [comment]
> Same error on our side

@fmauri-shippypro I reverted to the prev version until fixed `gregsdennis/dependencies-action@4fc2a4879387b43f784920699cb9303dd0524ac4`

**Comment by gregsdennis** [comment]
v1.4.1 seems to fix the problem @jon-nfc & @fmauri-shippypro.

I reverted the node pkg updates but kept the action changes.

**Comment by jon-nfc** [comment]
G'Day @gregsdennis 

Can confirm that v1.4.1 does indeed fix the problem and is working.

action updated with `uses: gregsdennis/dependencies-action@ae6e0529ef70f1366a21972f40b1ad0e1b5e3218     # v1.4.1`

Thank you for actioning so fast.
